language: go
services:
  - docker
# Needed for e2e tests
sudo: true
go_import_path: github.com/kubernetes-csi/kubernetes-csi
go: 1.10.3
install:
  # Must ensure that the code is available where Go expects it (necessary when testing a fork).
  - if ! [ -d "${GOPATH}/src/github.com/kubernetes-csi/kubernetes-csi" ]; then
      mkdir -p "${GOPATH}/src/github.com/kubernetes-csi/" &&
      ln -s "${TRAVIS_BUILD_DIR}" "${GOPATH}/src/github.com/kubernetes-csi/kubernetes-csi";
    fi
  - make
script:
  - make test
  - ./hack/e2e-hostpath.sh
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${DOCKER_USERNAME}" ] && [ "${DOCKER_PASSWORD}" ]; then
      docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" quay.io && make push;
    fi
