kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv2 
  annotations:
    volume.beta.kubernetes.io/storage-class: mrflexy 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
